### PR TITLE
change when press “Space2Study” logo buttom page scrooll to the top

### LINKED ISSUE #65: [Home page] The “Space2Study” logo button does not return to the home page welcoming block after clicking it.
**Description**: The “Space2Study” logo button does not return to the home page welcoming block after clicking it.

**Environment**: Windows 10 x64, Microsoft Edge 112.0.1722.48, Google Chrome 112.0.5615.122, MacOS Big Sur 11.7.3 Safari 16.3 (16614.4.6.11.6, 16614)

**Reproducible**: always.

**Preconditions:**
The client site is opened.
The user is not logged in.

**Steps to reproduce:**
1. Scroll down to the “How it works” block on the home page.
2. Click on the “Space2Study” logo button on the header.
3. Take a look at the home page.

**Actual result:**
The “Space2Study” logo button does **NOT** return to the home page welcoming block after clicking it.
**Expected result:**
The system scrolls back to the home page welcoming block after clicking on the “Space2Study” logo button on the header.

**Attachments:**

https://user-images.githubusercontent.com/129896611/233662817-59985b87-5e26-4970-9039-76b8419d3ce8.mov

### PR DESCRIPTION
**Pull request by LeonidShamarin**
Close #65 
The system scrolls back to the home page welcoming block after clicking on the “Space2Study” logo button on the header.
Return to the previous commit, make new branch from my previous

https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/122298176/a17d47c8-ec0d-4786-b69a-47b18d1bfa96

### CODE REVIEW

**Comment by vlad-khrychov** [comment]
Please, don`t create new PR-s when added commits. For one task we create one PR.

File: src/components/scroll-to-top-button/ScrollToTopButton.jsx [hunk 1]
```diff
@@ -11,6 +11,7 @@ const ScrollToTopButton = ({ element }) => {
       behavior: 'smooth'
     })
   }
+  ScrollToTopButton.goToTop = goToTop
```
Comment (vlad-khrychov) [inline src/components/scroll-to-top-button/ScrollToTopButton.jsx]: It is not convenient way to export of function

File: src/containers/layout/navbar/NavBar.jsx [hunk 2]
```diff
@@ -45,6 +49,10 @@ const Navbar = () => {
     return Object.values(authRoutes.accountMenu)
   }, [userRole])
 
+  const handleLogoClick = () => {
+    ScrollToTopButton.goToTop(mainWithFooter)
```
Comment (vlad-khrychov) [inline src/containers/layout/navbar/NavBar.jsx]: For now `goToTop` don`t obtain any arguments, but it will be correct way to call it when we change function.

File: src/containers/layout/navbar/NavBar.jsx [hunk 3]
```diff
@@ -70,9 +78,11 @@ const Navbar = () => {
   })
 
   return (
-    <Box sx={styles.header}>
+    <Box ref={mainWithFooter} sx={styles.header}>
+      <ScrollToTopButton element={mainWithFooter} />
```
Comment (vlad-khrychov) [inline src/containers/layout/navbar/NavBar.jsx]: We must not use this component here

**Review by vlad-khrychov — CHANGES_REQUESTED** [review]

File: src/components/scroll-to-top-button/ScrollToTopButton.jsx (hunk 1 above)
Comment (LeonidShamarin) [reply src/components/scroll-to-top-button/ScrollToTopButton.jsx]: It was deleted, I resolved it in another way

File: src/containers/layout/navbar/NavBar.jsx (hunk 2 above)
Comment (LeonidShamarin) [reply src/containers/layout/navbar/NavBar.jsx]: It was deleted, I resolved it in another way

File: src/containers/layout/navbar/NavBar.jsx (hunk 3 above)
Comment (LeonidShamarin) [reply src/containers/layout/navbar/NavBar.jsx]: It was deleted, I resolved it in another way

File: src/containers/layout/navbar/NavBar.jsx
Comment (AndriiNasadiuk) [inline src/containers/layout/navbar/NavBar.jsx:1]: Did it really need to be changed homePath to welcome route? UI behavior the same with welcome and home. (rows 33- 53)

**Review by AndriiNasadiuk — CHANGES_REQUESTED** [review]
Did it really need to be changed homePath to welcome route? UI behavior the same with welcome and home routes. And it isn’t  required in task. (rows 33- 53)

**Comment by LeonidShamarin** [comment]
> Did it really need to be changed homePath to welcome route? UI behavior the same with welcome and home routes. And it isn’t required in task. (rows 33- 53)

It says there, - "the system scrolls back to the home page welcoming block", and I write specific  route to welcome block

**Comment by AndriiNasadiuk** [comment]
> > Did it really need to be changed homePath to welcome route? UI behavior the same with welcome and home routes. And it isn’t required in task. (rows 33- 53)
> 
> It says there, - "the system scrolls back to the home page welcoming block", and I write specific route to welcome block



> welcoming

Can’t see where is written you have to change route to welcome. In my point of view it seems to scroll UI to the top of home page, not to some route

File: src/containers/layout/navbar/NavBar.jsx
Comment (AndriiNasadiuk) [inline src/containers/layout/navbar/NavBar.jsx:1]: do we really need to change home route path to welcome route path? rows 32 - 35

**Review by AndriiNasadiuk — APPROVED** [review]
ok

**Review by ArtemHolikov — APPROVED** [review]
Nice. Now looks better

**Review by Mygal-Alex — APPROVED** [review]
Now looks good

**Review by marianamartsy — APPROVED** [review]
ok

**Review by vlad-khrychov — APPROVED** [review]
